steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "${_IMAGE}", "-f", "deploy/Dockerfile.console", "."]
images:
  - ${_IMAGE}
substitutions:
  _REGION: us-central1
  _IMAGE: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/astraea/console:latest
timeout: 1200s
