steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "${_IMAGE}", "-f", "deploy/Dockerfile.console", "."]
images:
  - ${_IMAGE}
substitutions:
  _IMAGE: gcr.io/${PROJECT_ID}/astraea-console
timeout: 1200s
